import { resourceManifest, resourceDimensions } from "./resources-manifest"

// Resolves Obsidian embed targets (`![[name.png]]`) to a web path using a
// build-time manifest (generated by scripts/copy-resources.mjs). No runtime fs,
// so the 195MB content/resources folder never needs to be bundled into the server.

/** Resolve an embed target (filename or relative path) to a /resources URL, or null. */
export const resolveResourceUrl = (target: string): string | null => {
  const cleaned = decodeURIComponent(target.trim()).toLowerCase()
  const rel =
    resourceManifest[cleaned] ?? resourceManifest[cleaned.split("/").pop() ?? cleaned]
  if (!rel) return null
  const encoded = rel.split("/").map(encodeURIComponent).join("/")
  return `/resources/${encoded}`
}

/** Intrinsic [width, height] of a /resources image URL, from the build-time manifest. */
export const resourceDimensionsOf = (url: string): [number, number] | null => {
  if (!url.startsWith("/resources/")) return null
  const rel = url
    .slice("/resources/".length)
    .split("/")
    .map(decodeURIComponent)
    .join("/")
  return resourceDimensions[rel] ?? null
}
