import { slugify } from "@/components/post/mdx-components"

export type Chapter = { id: string; title: string; level: number }

/** Strip inline Markdown (bold/italic/code/links) so ToC labels read cleanly. */
const stripInlineMarkdown = (text: string): string =>
  text
    .replace(/\[([^\]]+)\]\([^)]*\)/g, "$1") // [label](url) → label
    .replace(/(\*\*|__)(.*?)\1/g, "$2") // **bold** / __bold__
    .replace(/(\*|_)(.*?)\1/g, "$2") // *italic* / _italic_
    .replace(/`([^`]+)`/g, "$1") // `code`
    .trim()

/**
 * Build a nested table of contents from `##` (level 2) and `###` (level 3)
 * Markdown headings. Skips fenced code blocks. Heading ids match the slugs
 * generated by AnchorHeading, with a numeric suffix for duplicate titles.
 */
export const extractChapters = (content: string): Chapter[] => {
  const chapters: Chapter[] = []
  const seen = new Map<string, number>()
  let inCode = false

  for (const line of content.split("\n")) {
    if (line.trim().startsWith("```")) inCode = !inCode
    if (inCode) continue

    const match = /^(#{2,3})\s+(.+)$/.exec(line)
    if (!match) continue

    const level = match[1].length
    const title = stripInlineMarkdown(match[2].trim())
    const base = slugify(title)
    const count = seen.get(base) ?? 0
    seen.set(base, count + 1)
    const id = count === 0 ? base : `${base}-${count}`
    chapters.push({ id, title, level })
  }

  return chapters
}
