import { defineConfig, globalIgnores } from "eslint/config"
import nextVitals from "eslint-config-next/core-web-vitals"
import nextTypescript from "eslint-config-next/typescript"

export default defineConfig([
  ...nextVitals,
  ...nextTypescript,
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by scripts/copy-resources.mjs on every dev/build run.
    "src/lib/resources-manifest.ts",
    // The Obsidian vault — prose, plus ~10k findings in bundled plugin JS.
    "content/**",
    "public/**",
  ]),
])
